Algunas formas de generar datasets para test y para training.

Usualmente la proporción es 80% - 20%


In [18]:
from sklearn.model_selection import train_test_split
import sklearn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
mainpath = '/mnt/c/Users/ruben/OneDrive/Documentos/MachineLearning/udemy/Machine_Learning_Introduction/datasets'
customer_churn_model_filename_csv = 'customer-churn-model/Customer Churn Model.txt'
customer_churn_model_csv = os.path.join(mainpath, customer_churn_model_filename_csv)
data = pd.read_csv(customer_churn_model_csv)

In [3]:
len(data)

3333

## Dividir utilizando la distribución normal

In [5]:
a = np.random.randn(len(data))

In [7]:
plt.hist(a)

(array([ 11.,  70., 291., 669., 965., 790., 419.,  97.,  19.,   2.]),
 array([-3.46446201, -2.71978404, -1.97510607, -1.2304281 , -0.48575013,
         0.25892784,  1.00360581,  1.74828378,  2.49296175,  3.23763972,
         3.98231769]),
 <BarContainer object of 10 artists>)

el 80% cae en True

In [8]:
check = (a < 0.8)
check

array([ True, False,  True, ...,  True,  True, False])

In [11]:
plt.hist(check.astype(int))

(array([ 708.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
        2625.]),
 array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]),
 <BarContainer object of 10 artists>)

In [12]:
check.mean()

0.7875787578757876

In [13]:
training = data[check]
testing = data[~check]

In [14]:
print(len(training))
print(len(testing))

2625
708


## usar la libreria sklearn

In [15]:
train, test = train_test_split(data, test_size=0.2)

In [16]:
print(len(train))
print(len(test))

2666
667


## Usando una función de shuffle

In [20]:
shuffle_data = sklearn.utils.shuffle(data)

In [21]:
cut_id = int(0.75 * len(shuffle_data))

train_data = shuffle_data[:cut_id ]
test_data = shuffle_data[cut_id+1:]

In [22]:
print(len(train_data))
print(len(test_data))

2499
833
